# Generated by Django 5.0.6 on 2024-06-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rsa_private_key',
        ),
    ]
