# Generated by Django 5.0.6 on 2024-06-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_customuser_rsa_private_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='signature',
        ),
    ]
