# Generated by Django 5.0.6 on 2024-06-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_message_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='encrypted_message',
            field=models.CharField(max_length=256),
        ),
    ]
