# Generated by Django 5.0.6 on 2024-06-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_message_encrypted_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='encrypted_des_key',
            field=models.CharField(max_length=1024),
        ),
    ]
